In [4]:
import scanpy as sc
import pandas as pd
import os

In [5]:
# Set correct path
base_path = r"C:\Users\annam\Downloads\GSE176078_Wu_etal_2021_BRCA_scRNASeq\Wu_etal_2021_BRCA_scRNASeq"

In [6]:
# Check files
print(os.listdir(base_path))

['count_matrix_barcodes.tsv', 'count_matrix_genes.tsv', 'count_matrix_sparse.mtx', 'metadata.csv']

In [7]:
# 1. Load matrix
adata = sc.read_mtx(base_path + r"\count_matrix_sparse.mtx")

In [9]:
# Load genes and barcodes
genes = pd.read_csv(base_path + r"\count_matrix_genes.tsv", header=None, sep="\t")
barcodes = pd.read_csv(base_path + r"\count_matrix_barcodes.tsv", header=None, sep="\t")

In [10]:
# Since matrix is genes x cells:
adata.obs_names = genes[0].astype(str)
adata.var_names = barcodes[0].astype(str)

In [11]:
# Transpose to cells x genes
adata = adata.T

In [12]:
# Now check
print(adata)
print(adata.obs_names[:5])
print(adata.var_names[:5])

AnnData object with n_obs × n_vars = 100064 × 29733
Index(['CID3586_AAGACCTCAGCATGAG', 'CID3586_AAGGTTCGTAGTACCT',
       'CID3586_ACCAGTAGTTGTGGCC', 'CID3586_ACCCACTAGATGTCGG',
       'CID3586_ACTGATGGTCAACTGT'],
      dtype='object')
Index(['RP11-34P13.7', 'FO538757.3', 'FO538757.2', 'AP006222.2',
       'RP4-669L17.10'],
      dtype='object')

In [13]:
meta = pd.read_csv(base_path + r"\metadata.csv")

print(meta.columns)
meta.head()

Index(['Unnamed: 0', 'orig.ident', 'nCount_RNA', 'nFeature_RNA',
       'percent.mito', 'subtype', 'celltype_subset', 'celltype_minor',
       'celltype_major'],
      dtype='object')

,Unnamed: 0,orig.ident,nCount_RNA,nFeature_RNA,percent.mito,subtype,celltype_subset,celltype_minor,celltype_major
0,CID3586_AAGACCTCAGCATGAG,CID3586,4581,1689,1.506221,HER2+,Endothelial ACKR1,Endothelial ACKR1,Endothelial
1,CID3586_AAGGTTCGTAGTACCT,CID3586,1726,779,5.793743,HER2+,Endothelial ACKR1,Endothelial ACKR1,Endothelial
2,CID3586_ACCAGTAGTTGTGGCC,CID3586,1229,514,1.383238,HER2+,Endothelial ACKR1,Endothelial ACKR1,Endothelial
3,CID3586_ACCCACTAGATGTCGG,CID3586,1352,609,1.923077,HER2+,Endothelial ACKR1,Endothelial ACKR1,Endothelial
4,CID3586_ACTGATGGTCAACTGT,CID3586,1711,807,13.325541,HER2+,Endothelial ACKR1,Endothelial ACKR1,Endothelial

In [14]:
# Set correct index
meta.index = meta["Unnamed: 0"].astype(str)

# Align metadata to AnnData
adata.obs = meta.loc[adata.obs_names]

In [16]:
# Add dataset label
adata.obs["dataset"] = "GSE176078"

# Clean names
adata.var_names_make_unique()
adata.obs_names_make_unique()

# Save
adata.write(r"C:\Users\annam\Dissertation 2026\GSE176078_raw.h5ad")

# Final check
print(adata)
adata.obs.head()

AnnData object with n_obs × n_vars = 100064 × 29733
    obs: 'Unnamed: 0', 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'percent.mito', 'subtype', 'celltype_subset', 'celltype_minor', 'celltype_major', 'dataset'

,Unnamed: 0,orig.ident,nCount_RNA,nFeature_RNA,percent.mito,subtype,celltype_subset,celltype_minor,celltype_major,dataset
CID3586_AAGACCTCAGCATGAG,CID3586_AAGACCTCAGCATGAG,CID3586,4581,1689,1.506221,HER2+,Endothelial ACKR1,Endothelial ACKR1,Endothelial,GSE176078
CID3586_AAGGTTCGTAGTACCT,CID3586_AAGGTTCGTAGTACCT,CID3586,1726,779,5.793743,HER2+,Endothelial ACKR1,Endothelial ACKR1,Endothelial,GSE176078
CID3586_ACCAGTAGTTGTGGCC,CID3586_ACCAGTAGTTGTGGCC,CID3586,1229,514,1.383238,HER2+,Endothelial ACKR1,Endothelial ACKR1,Endothelial,GSE176078
CID3586_ACCCACTAGATGTCGG,CID3586_ACCCACTAGATGTCGG,CID3586,1352,609,1.923077,HER2+,Endothelial ACKR1,Endothelial ACKR1,Endothelial,GSE176078
CID3586_ACTGATGGTCAACTGT,CID3586_ACTGATGGTCAACTGT,CID3586,1711,807,13.325541,HER2+,Endothelial ACKR1,Endothelial ACKR1,Endothelial,GSE176078